# Generated by Django 6.0.2 on 2026-02-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='related_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
