# Generated by Django 6.0.2 on 2026-03-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_llmprompt_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('ai_processing', 'Análisis con IA'), ('external_ai', 'Procesamiento por IA externa'), ('analytics', 'Analytics de uso')], max_length=50)),
                ('granted', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', help_text='Versión de la política de privacidad', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Ver datos'), ('export', 'Exportar datos'), ('delete', 'Eliminar datos'), ('modify', 'Modificar datos'), ('consent_change', 'Cambio de consentimiento'), ('login', 'Inicio de sesión')], max_length=50)),
                ('resource', models.CharField(help_text="Recurso accedido (ej: 'transactions', 'user_data')", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Metadata no sensible sobre la acción', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx')],
            },
        ),
    ]
