# Generated by Django 4.2.30 on 2026-09-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userconsent_consent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='consent_type',
            field=models.CharField(choices=[('terms_accepted', 'Términos y condiciones'), ('ai_processing', 'Análisis con IA'), ('external_ai', 'Procesamiento por IA externa'), ('analytics', 'Analytics de uso'), ('open_banking', 'Acceso a datos bancarios (Open Banking)')], max_length=50),
        ),
    ]
