# Generated by Django 4.2.30 on 2026-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userconsent_consent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured notification metadata (card, bank, tags, etc.)'),
        ),
    ]
