# Generated by Django 4.2.30 on 2026-09-22 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_transaction_client_id_transaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aeat_code',
            field=models.CharField(blank=True, help_text='Código casilla AEAT (ej. DONACION_0722, ALQUILER_0102)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tax_deductible',
            field=models.BooleanField(default=False, help_text='Indica si esta categoría desgrava o deduce en el IRPF'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_tax_deductible',
            field=models.BooleanField(default=False, help_text='Marcado explícito como deducible en IRPF'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_tags',
            field=models.JSONField(blank=True, default=list, help_text="Etiquetas fiscales (ej. ['Renta2025', 'DonacionCruzRoja'])"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_year',
            field=models.IntegerField(blank=True, help_text='Ejercicio fiscal (ej. 2025). Si está vacío se asume el año de la fecha.', null=True),
        ),
        migrations.CreateModel(
            name='TaxFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('aeat_box', models.CharField(blank=True, help_text='Referencia a la casilla AEAT (ej. Casilla 722)', max_length=150)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Configuración de filtros JSON')),
                ('is_system_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_system_preset', 'name'],
            },
        ),
    ]
