# Generated by Django 4.2.30 on 2026-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash SHA-256 de este evento', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 del registro anterior', max_length=64),
        ),
    ]
