# Generated by Django 4.2.30 on 2026-09-20 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_alter_userconsent_consent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('redsys', 'Redsys'), ('powens', 'Powens'), ('truelayer', 'TrueLayer')], max_length=50)),
                ('provider_connection_id', models.CharField(blank=True, max_length=255)),
                ('institution_id', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('expired', 'Expirada'), ('error', 'Error'), ('revoked', 'Revocada')], default='pending', max_length=20)),
                ('access_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('refresh_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('consent_id', models.CharField(blank=True, max_length=255)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Provider-specific data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Programada'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('success', 'Éxito'), ('error', 'Error')], default='running', max_length=20)),
                ('accounts_synced', models.IntegerField(default=0)),
                ('transactions_added', models.IntegerField(default=0)),
                ('transactions_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='banking.bankconnection')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(max_length=255, unique=True)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name_encrypted', models.BinaryField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, help_text='checking, savings, credit_card...', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Linked local account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account_link', to='api.account')),
                ('bank_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='banking.bankconnection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('category_code', models.CharField(blank=True, help_text='Category from bank/provider', max_length=50)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='banking.bankaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction_link', to='api.transaction')),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
                'indexes': [models.Index(fields=['bank_account', 'booking_date'], name='banking_ban_bank_ac_48a7c9_idx')],
                'unique_together': {('bank_account', 'external_transaction_id')},
            },
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['user', 'status'], name='banking_ban_user_id_539e2f_idx'),
        ),
    ]
