# Generated by Django 4.2.30 on 2026-09-22 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_category_aeat_code_category_tax_deductible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('access_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('refresh_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_query', models.CharField(default='has:attachment (filename:pdf OR filename:png OR filename:jpg OR filename:jpeg)', help_text='Filtro de búsqueda de mensajes en Gmail', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path)),
                ('storage_path', models.CharField(blank=True, help_text='Ruta en storage local o bucket GCS', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='Tamaño en bytes')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 para evitar duplicados', max_length=64)),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=100)),
                ('gmail_web_link', models.URLField(blank=True, help_text='Enlace directo a Gmail web', max_length=500)),
                ('email_subject', models.CharField(blank=True, max_length=300)),
                ('email_sender', models.CharField(blank=True, max_length=255)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('amount_hint', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('unmatched', 'Sin vincular'), ('suggested', 'Sugerencia pendiente'), ('auto_matched', 'Vinculación directa automática'), ('confirmed', 'Confirmado manual')], default='unmatched', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_transaction', models.ForeignKey(blank=True, help_text='Transacción propuesta para coincidencia pendiente de confirmación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='api.transaction')),
                ('transaction', models.ForeignKey(blank=True, help_text='Transacción vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
